"""add resolved_at to tickets

Revision ID: 3d70b365a85a
Revises: d96ba066f290
Create Date: 2026-09-29 10:21:44.468190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d70b365a85a'
down_revision: Union[str, Sequence[str], None] = 'd96ba066f290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'resolved_at')
    # ### end Alembic commands ###
