"""add required timestamps and AI ticket fields

Revision ID: a327f936950b
Revises: 36733c1de750
Create Date: 2026-09-24 16:18:05.059827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a327f936950b'
down_revision: Union[str, Sequence[str], None] = '36733c1de750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_messages', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tickets', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('ai_suggested_action', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('tickets', 'ai_suggested_action')
    op.drop_column('tickets', 'ai_summary')
    op.drop_column('ticket_messages', 'timestamp')
    # ### end Alembic commands ###
